version: '3'

networks:
  story_net:
    driver: bridge

volumes:
  dbdata:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./dbdata

services:
  database:
    hostname: postgresdb
    image: postgres:13
    volumes:
      - dbdata:/var/lib/postgresql/data
    restart: always
    ports:
      - '5432:5432'
    networks:
      - story_net
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
  app:
    hostname: beapp
    build: .
    networks:
      - story_net
    depends_on:
      - database
    ports:
      - '8080:8080'
    restart: always
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
  nginx:
    image: nginx
    hostname: nginxproxy
    networks:
      - story_net
    restart: always
    volumes:
      - ./nginx-selfsigned.crt:/etc/nginx/cert.crt
      - ./nginx-selfsigned.key:/etc/nginx/cert.key
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '80:80'
      - '443:443'