spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgres://ec2-54-204-148-110.compute-1.amazonaws.com:5432/db46m5s6n5kcmp
    username: nwovwyidthoeaa
    password: 13ad69b50909b7ef7178ac3420ce22be6f01dd96b8aacef9ebf312eb1c094044
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 10
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
