spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./data/demo
    username: dbmaster
    password: dbmaster
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 10
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
#    open-in-view: false
    properties:
      hibernate:
        generate_statistics: true